// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Sign out of the open synced profile's account: revoke the session on the
/// server (best effort offline), forget the tokens, stop sync. Local data
/// stays; `sync_reauthenticate` signs in again. Emits `signed_out`.
Future<void> accountLogout() => RustLib.instance.api.crateApiAccountAccountLogout();

/// Ask the server to send an account password-reset e-mail (always
/// accepted). No profile needed; does not grant vault access.
Future<void> accountRequestPasswordReset({required String serverUrl, required String email}) =>
    RustLib.instance.api.crateApiAccountAccountRequestPasswordReset(serverUrl: serverUrl, email: email);

/// Change the account password (`invalid_credentials` + reason
/// `current_password_wrong`, `invalid_input` + reason
/// `account_password_too_short` below 12 characters).
Future<void> accountChangePassword({required List<int> current, required List<int> next}) =>
    RustLib.instance.api.crateApiAccountAccountChangePassword(current: current, next: next);

/// **Explicit user action only** (Reveal / Copy): the secret of a password
/// or key credential as UTF-8 bytes, returned once. app-core zeroizes its
/// copies and logs an audit line without the value; the buffer handed to
/// FRB is not zeroized by FRB (ADR-0101 §6 limit) — wipe the Dart copy
/// (`SecretText`) after use.
Future<Uint8List> credentialsRevealSecret({required String credentialId}) =>
    RustLib.instance.api.crateApiAccountCredentialsRevealSecret(credentialId: credentialId);
