// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `context`, `parse_snippet_type`, `target`

/// Check a provider (models, capabilities, latency) → `AiProviderTestDto`.
Future<String> aiTestProvider({required String providerId}) =>
    RustLib.instance.api.crateApiAiAiTestProvider(providerId: providerId);

/// Ask AI. The stream starts with
/// `{"type":"started","request_id":…,"conversation_id":…}`, then `AiAskChunk`
/// items, ending with exactly one `done` or `error`.
Stream<String> aiAsk({String? providerId, String? conversationId, required String question, String? contextJson}) =>
    RustLib.instance.api.crateApiAiAiAsk(
      providerId: providerId,
      conversationId: conversationId,
      question: question,
      contextJson: contextJson,
    );

/// Abort a running Ask request. `false` if it already finished.
Future<bool> aiCancel({required String requestId}) => RustLib.instance.api.crateApiAiAiCancel(requestId: requestId);

/// "Generate command" → `CommandProposalDto` (never executed here).
Future<String> aiGenerateCommand({
  String? providerId,
  required String request,
  String? snippetType,
  String? contextJson,
}) => RustLib.instance.api.crateApiAiAiGenerateCommand(
  providerId: providerId,
  request: request,
  snippetType: snippetType,
  contextJson: contextJson,
);

/// "Convert command into a parameterized snippet" → `SnippetDraftDto`
/// (local parsing; the LLM refines it when `use_llm`).
Future<String> aiConvertToSnippet({
  String? providerId,
  required String command,
  String? snippetType,
  required bool useLlm,
}) => RustLib.instance.api.crateApiAiAiConvertToSnippet(
  providerId: providerId,
  command: command,
  snippetType: snippetType,
  useLlm: useLlm,
);

/// Local risk rules (no provider involved) → `RiskAssessmentDto`.
Future<String> aiAssessRisk({required String command, String? snippetType, String? shell}) =>
    RustLib.instance.api.crateApiAiAiAssessRisk(command: command, snippetType: snippetType, shell: shell);
