// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `app_config`, `info`, `os_auth`, `read_store`, `ui_store_path`, `write_store`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Report what the OS can do for user-presence checks (`None` = nothing;
/// `not_enrolled` = hardware without enrolled biometrics / passcode).
void osAuthReport({OsAuthKindChoice? kind, required bool notEnrolled}) =>
    RustLib.instance.api.crateApiAppOsAuthReport(kind: kind, notEnrolled: notEnrolled);

/// Create the global core (idempotent: a running core is kept, e.g. after a
/// Flutter hot restart). Call once at start-up, before anything else.
Future<CoreInfo> coreInit({required CoreConfig config}) => RustLib.instance.api.crateApiAppCoreInit(config: config);

/// Close the open profile (locks the vault, stops sync/SSH, closes the
/// SQLCipher connection) and drop the core. Call before the process exits.
Future<void> coreShutdown() => RustLib.instance.api.crateApiAppCoreShutdown();

bool coreIsInitialized() => RustLib.instance.api.crateApiAppCoreIsInitialized();

String coreDataDir() => RustLib.instance.api.crateApiAppCoreDataDir();

/// App events (`AppEvent` JSON, serde tag `type`). A `{"type":"lagged"}`
/// item means events were dropped: re-read everything.
Stream<String> coreEvents() => RustLib.instance.api.crateApiAppCoreEvents();

/// Questions the UI must answer (`PromptRequest` JSON:
/// `{"HostKey":{..}}`, `{"Passphrase":{..}}`, `{"Password":{..}}`) — for
/// terminals, SFTP, tunnels and exec alike (the Dart `PromptService` shows
/// the ones no terminal tab claims). Subscribe before connecting: without a
/// subscriber prompts are declined.
Stream<String> corePrompts() => RustLib.instance.api.crateApiAppCorePrompts();

Future<void> promptAnswerHostKey({required String requestId, required HostKeyAnswer answer}) =>
    RustLib.instance.api.crateApiAppPromptAnswerHostKey(requestId: requestId, answer: answer);

/// `None` cancels. Used for this connection only, never stored.
Future<void> promptAnswerPassword({required String requestId, Uint8List? password}) =>
    RustLib.instance.api.crateApiAppPromptAnswerPassword(requestId: requestId, password: password);

/// `None` cancels.
Future<void> promptAnswerPassphrase({required String requestId, Uint8List? passphrase}) =>
    RustLib.instance.api.crateApiAppPromptAnswerPassphrase(requestId: requestId, passphrase: passphrase);

/// `GET /v1/meta` of a server (no account needed) → `ServerInfo` JSON.
Future<String> serverProbe({required String serverUrl, required String clientVersion}) =>
    RustLib.instance.api.crateApiAppServerProbe(serverUrl: serverUrl, clientVersion: clientVersion);

/// Device-local, **non-secret** UI state (`<data dir>/ui-state.json`):
/// `LocalSettings` (language, theme, …), backup schedules, the list of
/// recent backups, pending Recovery Kit checks. Never synced.
Future<String?> uiStoreGet({required String key}) => RustLib.instance.api.crateApiAppUiStoreGet(key: key);

/// Set (`Some`) or remove (`None`) a key of the device-local UI store.
Future<void> uiStoreSet({required String key, String? value}) =>
    RustLib.instance.api.crateApiAppUiStoreSet(key: key, value: value);

/// Start-up configuration from Dart.
class CoreConfig {
  /// Data root; `None` = `CONSOLECRYPT_DATA_DIR` or the platform default.
  final String? dataDir;
  final SecureStoreChoice secureStore;

  /// Keychain service name; `None` = `io.consolecrypt.ConsoleCrypt`.
  final String? keychainService;
  final KdfChoice kdf;

  /// App version (`x-cc-client-version`, backups).
  final String clientVersion;

  /// Default device name for registrations; `None` = host name.
  final String? deviceName;
  final bool backgroundSync;
  final bool autoStartTunnels;

  /// `tracing` directives (stderr); `None` = `CC_LOG` or app-core defaults.
  final String? logDirectives;

  const CoreConfig({
    this.dataDir,
    required this.secureStore,
    this.keychainService,
    required this.kdf,
    required this.clientVersion,
    this.deviceName,
    required this.backgroundSync,
    required this.autoStartTunnels,
    this.logDirectives,
  });

  @override
  int get hashCode =>
      dataDir.hashCode ^
      secureStore.hashCode ^
      keychainService.hashCode ^
      kdf.hashCode ^
      clientVersion.hashCode ^
      deviceName.hashCode ^
      backgroundSync.hashCode ^
      autoStartTunnels.hashCode ^
      logDirectives.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreConfig &&
          runtimeType == other.runtimeType &&
          dataDir == other.dataDir &&
          secureStore == other.secureStore &&
          keychainService == other.keychainService &&
          kdf == other.kdf &&
          clientVersion == other.clientVersion &&
          deviceName == other.deviceName &&
          backgroundSync == other.backgroundSync &&
          autoStartTunnels == other.autoStartTunnels &&
          logDirectives == other.logDirectives;
}

/// Result of [`core_init`].
class CoreInfo {
  final String dataDir;

  /// `macos` | `windows` | `linux`.
  final String platform;
  final String coreVersion;

  /// The core was already running (Flutter hot restart); config ignored.
  final bool alreadyInitialized;

  const CoreInfo({
    required this.dataDir,
    required this.platform,
    required this.coreVersion,
    required this.alreadyInitialized,
  });

  @override
  int get hashCode => dataDir.hashCode ^ platform.hashCode ^ coreVersion.hashCode ^ alreadyInitialized.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreInfo &&
          runtimeType == other.runtimeType &&
          dataDir == other.dataDir &&
          platform == other.platform &&
          coreVersion == other.coreVersion &&
          alreadyInitialized == other.alreadyInitialized;
}

/// Answer to an unknown-host-key prompt.
enum HostKeyAnswer { acceptAndSave, acceptOnce, reject }

/// Argon2id cost for new password envelopes.
enum KdfChoice {
  /// Calibrate on this machine (production, ~0.75 s).
  calibrate,

  /// ADR-0002 default parameters.
  standard,

  /// Server floor — tests only.
  floor,
}

/// What the OS offers for user-presence checks (reported by the UI after
/// querying LocalAuthentication / Windows Hello).
enum OsAuthKindChoice {
  touchId,
  faceId,
  windowsHello,

  /// OS account password / PIN.
  deviceCredential,
}

/// Where the core keeps database keys, device identities and tokens.
enum SecureStoreChoice {
  /// OS keychain (macOS Keychain / Windows Credential Manager). Production.
  os,

  /// Process memory only — nothing survives a restart (tests, demos).
  memory,
}
