// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `inspect_file`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Write the open vault to `path` → `BackupSummaryDto`.
Future<String> backupExport({required String path}) => RustLib.instance.api.crateApiBackupBackupExport(path: path);

/// Read a backup's header without decrypting anything.
Future<BackupHeader> backupInspect({required String path}) =>
    RustLib.instance.api.crateApiBackupBackupInspect(path: path);

/// The open profile's backup schedule → `BackupScheduleDto` (stored in the
/// profile; the core runs due backups while unlocked, also with the window
/// hidden).
Future<String> backupScheduleGet() => RustLib.instance.api.crateApiBackupBackupScheduleGet();

/// Replace the schedule (`BackupScheduleDto` JSON) → the stored schedule
/// (next run computed by the core).
Future<String> backupScheduleSet({required String scheduleJson}) =>
    RustLib.instance.api.crateApiBackupBackupScheduleSet(scheduleJson: scheduleJson);

/// Run the scheduled backup now (retention applied) → `BackupInfoDto`.
Future<String> backupNow() => RustLib.instance.api.crateApiBackupBackupNow();

/// Backups written on this device for the open profile →
/// `Vec<BackupInfoDto>` (newest first).
Future<String> backupRecent() => RustLib.instance.api.crateApiBackupBackupRecent();

/// Add entries (`Vec<BackupInfoDto>` JSON) to the recent list (one-time
/// import of the list the UI kept before the core did).
Future<void> backupRemember({required String backupsJson}) =>
    RustLib.instance.api.crateApiBackupBackupRemember(backupsJson: backupsJson);

/// Restore into a **new Local profile** (active, unlocked) →
/// `CreatedProfile`.
Future<String> backupImport({
  required String path,
  required String displayName,
  required BackupUnlockKind unlockKind,
  required List<int> secret,
  Uint8List? newPassphrase,
}) => RustLib.instance.api.crateApiBackupBackupImport(
  path: path,
  displayName: displayName,
  unlockKind: unlockKind,
  secret: secret,
  newPassphrase: newPassphrase,
);

/// Header facts of a backup file (nothing is decrypted).
class BackupHeader {
  final String path;
  final String vaultId;
  final int createdAtMs;
  final int objects;
  final int sizeBytes;

  /// e.g. `ccbackup-v1`.
  final String format;
  final String appVersion;

  const BackupHeader({
    required this.path,
    required this.vaultId,
    required this.createdAtMs,
    required this.objects,
    required this.sizeBytes,
    required this.format,
    required this.appVersion,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      vaultId.hashCode ^
      createdAtMs.hashCode ^
      objects.hashCode ^
      sizeBytes.hashCode ^
      format.hashCode ^
      appVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupHeader &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          vaultId == other.vaultId &&
          createdAtMs == other.createdAtMs &&
          objects == other.objects &&
          sizeBytes == other.sizeBytes &&
          format == other.format &&
          appVersion == other.appVersion;
}

/// How a backup being restored is opened.
enum BackupUnlockKind {
  passphrase,

  /// 24 words or the recovery QR text (a new passphrase must be set).
  recoveryKey,
}
