// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `invalid`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// `Vec<CredentialDto>`.
Future<String> credentialsList() => RustLib.instance.api.crateApiCredentialsCredentialsList();

Future<String> credentialsAddPassword({required String name, String? username, required List<int> password}) =>
    RustLib.instance.api.crateApiCredentialsCredentialsAddPassword(name: name, username: username, password: password);

Future<String> credentialsGenerateKey({
  required String name,
  String? username,
  required KeyGenChoice algorithm,
  Uint8List? passphrase,
  required bool rememberPassphrase,
}) => RustLib.instance.api.crateApiCredentialsCredentialsGenerateKey(
  name: name,
  username: username,
  algorithm: algorithm,
  passphrase: passphrase,
  rememberPassphrase: rememberPassphrase,
);

Future<String> credentialsImportKey({
  required String name,
  String? username,
  required List<int> privateKey,
  Uint8List? passphrase,
  required bool rememberPassphrase,
  String? certificate,
}) => RustLib.instance.api.crateApiCredentialsCredentialsImportKey(
  name: name,
  username: username,
  privateKey: privateKey,
  passphrase: passphrase,
  rememberPassphrase: rememberPassphrase,
  certificate: certificate,
);

/// OS agent (`agent_path = None`) or an external agent socket / pipe.
Future<String> credentialsAddAgent({required String name, String? username, String? agentPath}) =>
    RustLib.instance.api.crateApiCredentialsCredentialsAddAgent(name: name, username: username, agentPath: agentPath);

/// Rename / username / certificate (`Some("")` removes the certificate).
Future<String> credentialsUpdate({required String id, required String name, String? username, String? certificate}) =>
    RustLib.instance.api.crateApiCredentialsCredentialsUpdate(
      id: id,
      name: name,
      username: username,
      certificate: certificate,
    );

Future<String> credentialsSetPassword({required String id, required List<int> password}) =>
    RustLib.instance.api.crateApiCredentialsCredentialsSetPassword(id: id, password: password);

Future<String> credentialsRememberPassphrase({required String id, required List<int> passphrase}) =>
    RustLib.instance.api.crateApiCredentialsCredentialsRememberPassphrase(id: id, passphrase: passphrase);

Future<String> credentialsForgetPassphrase({required String id}) =>
    RustLib.instance.api.crateApiCredentialsCredentialsForgetPassphrase(id: id);

/// Refused (`in_use`) while hosts/groups use it; removes its Secrets.
Future<void> credentialsDelete({required String id}) =>
    RustLib.instance.api.crateApiCredentialsCredentialsDelete(id: id);

/// OpenSSH public key line of a key credential (not secret).
Future<String> credentialsPublicKey({required String id}) =>
    RustLib.instance.api.crateApiCredentialsCredentialsPublicKey(id: id);

/// Parse a pasted OpenSSH / PEM / PuTTY private key without importing it
/// or removing its protection. The input buffer is zeroized afterwards.
Future<KeyInspectionResult> credentialsInspectKey({required List<int> privateKey}) =>
    RustLib.instance.api.crateApiCredentialsCredentialsInspectKey(privateKey: privateKey);

/// Algorithms offered by "Generate key" (CLIENT_SPEC §7.1).
enum KeyGenChoice { ed25519, rsa3072, rsa4096 }

/// Non-secret facts about a pasted private key (nothing is imported).
class KeyInspectionResult {
  final bool valid;

  /// cc-models `KeyAlgorithm` wire name (`ed25519`, `rsa3072`, …).
  final String? algorithm;
  final bool encrypted;
  final String? fingerprint;
  final String? publicKey;

  /// Why the key is not valid (never contains key material).
  final String? error;

  const KeyInspectionResult({
    required this.valid,
    this.algorithm,
    required this.encrypted,
    this.fingerprint,
    this.publicKey,
    this.error,
  });

  @override
  int get hashCode =>
      valid.hashCode ^
      algorithm.hashCode ^
      encrypted.hashCode ^
      fingerprint.hashCode ^
      publicKey.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyInspectionResult &&
          runtimeType == other.runtimeType &&
          valid == other.valid &&
          algorithm == other.algorithm &&
          encrypted == other.encrypted &&
          fingerprint == other.fingerprint &&
          publicKey == other.publicKey &&
          error == other.error;
}
