// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> enrollmentGrants({required String id}) =>
    RustLib.instance.api.crateApiEnrollmentEnrollmentGrants(id: id);

Future<String> enrollmentCreate({required String id, required String createJson}) =>
    RustLib.instance.api.crateApiEnrollmentEnrollmentCreate(id: id, createJson: createJson);

Future<String> enrollmentRevoke({required String id, required String grantId}) =>
    RustLib.instance.api.crateApiEnrollmentEnrollmentRevoke(id: id, grantId: grantId);

Future<String> enrollmentExport({required String id, required String grantId}) =>
    RustLib.instance.api.crateApiEnrollmentEnrollmentExport(id: id, grantId: grantId);

Future<String> enrollmentPrepare({required String bundle, required bool editor}) =>
    RustLib.instance.api.crateApiEnrollmentEnrollmentPrepare(bundle: bundle, editor: editor);

Future<String> enrollmentInspect({required String bundle}) =>
    RustLib.instance.api.crateApiEnrollmentEnrollmentInspect(bundle: bundle);

Future<String> enrollmentEndorse({required String bundle, required String confirmedCode}) =>
    RustLib.instance.api.crateApiEnrollmentEnrollmentEndorse(bundle: bundle, confirmedCode: confirmedCode);

Future<String> enrollmentSubmit({required String bundle, required String confirmedCode}) =>
    RustLib.instance.api.crateApiEnrollmentEnrollmentSubmit(bundle: bundle, confirmedCode: confirmedCode);

Future<String> enrollmentRequests({required String id}) =>
    RustLib.instance.api.crateApiEnrollmentEnrollmentRequests(id: id);

Future<String> enrollmentPending() => RustLib.instance.api.crateApiEnrollmentEnrollmentPending();

Future<String> enrollmentChallenge({required String id, required String requestId}) =>
    RustLib.instance.api.crateApiEnrollmentEnrollmentChallenge(id: id, requestId: requestId);

Future<String> enrollmentRespond({required String id, required String requestId}) =>
    RustLib.instance.api.crateApiEnrollmentEnrollmentRespond(id: id, requestId: requestId);

Future<String> enrollmentAccept({required String id, required String requestId, required bool confirmedManual}) =>
    RustLib.instance.api.crateApiEnrollmentEnrollmentAccept(
      id: id,
      requestId: requestId,
      confirmedManual: confirmedManual,
    );

Future<String> enrollmentProcessAutomatic() => RustLib.instance.api.crateApiEnrollmentEnrollmentProcessAutomatic();

Future<String> enrollmentReconcile({required String id, required String confirmedOwnerCode}) =>
    RustLib.instance.api.crateApiEnrollmentEnrollmentReconcile(id: id, confirmedOwnerCode: confirmedOwnerCode);

Future<String> enrollmentRestorePairing({required String bundle, required String confirmedCode}) =>
    RustLib.instance.api.crateApiEnrollmentEnrollmentRestorePairing(bundle: bundle, confirmedCode: confirmedCode);
