// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_info`, `internal`, `invalid`, `new`, `not_initialized`, `with`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `fmt`, `from`

/// Error of any bridge function (Dart: thrown `BridgeError`, mapped to
/// `AppException` in `lib/core/bridge/mapping.dart`).
///
/// * `code` — app-core's stable [`AppError::code`] (ADR-0107) or a bridge
///   code: `not_initialized`, `internal`.
/// * `message` — English, secret-free diagnostic (never the primary UI text).
/// * `reason` — optional refinement: `AppError::reason`, the wire name of
///   the Dart `AppErrorReason` (`current_passphrase_wrong`, `host_not_found`,
///   `directory_not_found`, …).
/// * `details` — `AppError::args`, non-secret structured data (`field`,
///   `rule`, `what`, `id`, `name`, `path`, `used_by`, `retry_after_seconds`,
///   `status`, `protocol_code`, `names`, `size`, `limit`, `diagnostic`, …);
///   the Dart side passes them as `AppException.args`.
class BridgeError implements FrbException {
  final String code;
  final String message;
  final String? reason;
  final Map<String, String> details;

  const BridgeError({required this.code, required this.message, this.reason, required this.details});

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ reason.hashCode ^ details.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          reason == other.reason &&
          details == other.details;
}
