// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `host_auth`, `host_exists`, `upsert_id`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`

/// `Vec<HostDto>` sorted by name.
Future<String> hostsList() => RustLib.instance.api.crateApiInventoryHostsList();

/// Insert or update a host (`HostDto` JSON) keeping `credential_id` as given.
Future<String> hostsSave({required String hostJson}) =>
    RustLib.instance.api.crateApiInventoryHostsSave(hostJson: hostJson);

/// Insert or update a host together with its authentication, atomically.
Future<String> hostsSaveWithAuth({required String hostJson, required HostAuthInput auth}) =>
    RustLib.instance.api.crateApiInventoryHostsSaveWithAuth(hostJson: hostJson, auth: auth);

/// Delete a host, its tunnels and its inline credential.
Future<void> hostsDelete({required String id}) => RustLib.instance.api.crateApiInventoryHostsDelete(id: id);

/// Planned route (`ConnectionRouteDto`: `user@hop -> … -> user@target`).
Future<String> hostsDescribeConnection({required String hostId}) =>
    RustLib.instance.api.crateApiInventoryHostsDescribeConnection(hostId: hostId);

/// Effective settings of a (possibly unsaved) host with provenance, the
/// expanded route and planner findings as codes → `PlanPreviewDto`
/// (host editor). Nothing is saved; no connection is made.
Future<String> hostsPlanPreview({required String hostJson}) =>
    RustLib.instance.api.crateApiInventoryHostsPlanPreview(hostJson: hostJson);

Future<String> groupsList() => RustLib.instance.api.crateApiInventoryGroupsList();

Future<String> groupsSave({required String groupJson}) =>
    RustLib.instance.api.crateApiInventoryGroupsSave(groupJson: groupJson);

/// Delete a group; its child groups and hosts move to its parent first
/// (the UI contract), then the group is removed.
Future<void> groupsDelete({required String id}) => RustLib.instance.api.crateApiInventoryGroupsDelete(id: id);

Future<String> jumpProfilesList() => RustLib.instance.api.crateApiInventoryJumpProfilesList();

Future<String> jumpProfilesSave({required String profileJson}) =>
    RustLib.instance.api.crateApiInventoryJumpProfilesSave(profileJson: profileJson);

Future<void> jumpProfilesDelete({required String id}) =>
    RustLib.instance.api.crateApiInventoryJumpProfilesDelete(id: id);

Future<String> tunnelsList() => RustLib.instance.api.crateApiInventoryTunnelsList();

Future<String> tunnelsSave({required String tunnelJson}) =>
    RustLib.instance.api.crateApiInventoryTunnelsSave(tunnelJson: tunnelJson);

/// Stop the tunnel if running, then delete it.
Future<void> tunnelsDelete({required String id}) => RustLib.instance.api.crateApiInventoryTunnelsDelete(id: id);

Future<String> snippetsList() => RustLib.instance.api.crateApiInventorySnippetsList();

Future<String> snippetsSave({required String snippetJson}) =>
    RustLib.instance.api.crateApiInventorySnippetsSave(snippetJson: snippetJson);

Future<void> snippetsDelete({required String id}) => RustLib.instance.api.crateApiInventorySnippetsDelete(id: id);

/// Snippet palette search (local FTS, semantic only with an embedding
/// provider, never an LLM) → `Vec<SnippetSearchHitDto>`. Empty query =
/// most used.
Future<String> snippetsSearch({required String query, required int limit}) =>
    RustLib.instance.api.crateApiInventorySnippetsSearch(query: query, limit: limit);

/// Render a (possibly unsaved) snippet with values (`{"name":"value"}`
/// JSON) using the core's quoting policy → `SnippetRenderDto`
/// (`command` or `field_errors`).
Future<String> snippetsRender({required String snippetJson, required String valuesJson}) =>
    RustLib.instance.api.crateApiInventorySnippetsRender(snippetJson: snippetJson, valuesJson: valuesJson);

Future<String> knownHostsList() => RustLib.instance.api.crateApiInventoryKnownHostsList();

Future<void> knownHostsRemove({required String id}) => RustLib.instance.api.crateApiInventoryKnownHostsRemove(id: id);

/// `VaultSettingsDto` (singleton).
Future<String> vaultSettingsGet() => RustLib.instance.api.crateApiInventoryVaultSettingsGet();

Future<String> vaultSettingsSave({required String settingsJson}) =>
    RustLib.instance.api.crateApiInventoryVaultSettingsSave(settingsJson: settingsJson);

Future<String> aiProvidersList() => RustLib.instance.api.crateApiInventoryAiProvidersList();

/// Save a provider config; `api_key` replaces the stored key (a Secret
/// object), `clear_api_key` removes it. The key is never returned.
Future<String> aiProvidersSave({required String providerJson, Uint8List? apiKey, required bool clearApiKey}) => RustLib
    .instance
    .api
    .crateApiInventoryAiProvidersSave(providerJson: providerJson, apiKey: apiKey, clearApiKey: clearApiKey);

Future<void> aiProvidersDelete({required String id}) => RustLib.instance.api.crateApiInventoryAiProvidersDelete(id: id);

/// Desired authentication of a host (sent with [`hosts_save_with_auth`]).
/// Secret-bearing: redacted `Debug`; the password buffer is moved into
/// app-core's zeroizing secret (or zeroized when unused).
class HostAuthInput {
  final HostAuthKind kind;
  final String? credentialId;

  /// Inline password (UTF-8), inbound only.
  final Uint8List? password;
  final String? agentPath;

  const HostAuthInput({required this.kind, this.credentialId, this.password, this.agentPath});

  @override
  int get hashCode => kind.hashCode ^ credentialId.hashCode ^ password.hashCode ^ agentPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostAuthInput &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          credentialId == other.credentialId &&
          password == other.password &&
          agentPath == other.agentPath;
}

/// How a host authenticates (`HostAuth` of app-core, flattened for FRB).
enum HostAuthKind {
  /// Inherit username/credential from the group chain.
  inherit,

  /// Link an existing (shared) credential: `credential_id`.
  credential,

  /// The host's own password credential: `password` (`None` keeps it).
  inlinePassword,

  /// Ask at connect; nothing stored.
  passwordPrompt,

  /// OS SSH agent.
  osAgent,

  /// External agent socket / pipe: `agent_path`.
  externalAgent,
}
