// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// All profiles (`Vec<ProfileInfo>`; details filled for the open one).
Future<String> profilesList() => RustLib.instance.api.crateApiProfilesProfilesList();

/// The profile remembered as active (to reopen at start-up).
Future<String?> profilesLastActiveId() => RustLib.instance.api.crateApiProfilesProfilesLastActiveId();

/// Open (switch to) a profile; its vault starts locked → `ProfileInfo`.
Future<String> profilesOpen({required String profileId}) =>
    RustLib.instance.api.crateApiProfilesProfilesOpen(profileId: profileId);

/// Close the open profile (locks the vault).
Future<void> profilesClose() => RustLib.instance.api.crateApiProfilesProfilesClose();

Future<String> profilesRename({required String profileId, required String displayName}) =>
    RustLib.instance.api.crateApiProfilesProfilesRename(profileId: profileId, displayName: displayName);

/// Delete a profile's database, index entry and keychain items.
Future<void> profilesRemove({required String profileId}) =>
    RustLib.instance.api.crateApiProfilesProfilesRemove(profileId: profileId);

/// New Local profile with its vault (active, unlocked) → `CreatedProfile`
/// (incl. the Recovery Kit to show once).
Future<String> profilesCreateLocal({required String displayName, required List<int> passphrase}) =>
    RustLib.instance.api.crateApiProfilesProfilesCreateLocal(displayName: displayName, passphrase: passphrase);

/// New Synced profile: register (`register = true`) or log in →
/// `SyncedAccountDto` (`vaults` empty → create one, else join).
Future<String> profilesCreateSynced({
  required String displayName,
  required String serverUrl,
  required String email,
  required List<int> password,
  required bool register,
}) => RustLib.instance.api.crateApiProfilesProfilesCreateSynced(
  displayName: displayName,
  serverUrl: serverUrl,
  email: email,
  password: password,
  register: register,
);

/// Vaults of the signed-in account (`Vec<RemoteVaultDto>`).
Future<String> profilesRemoteVaults() => RustLib.instance.api.crateApiProfilesProfilesRemoteVaults();

/// Create the vault of a synced profile that has none → `RecoveryKitDto`.
Future<String> vaultCreate({required List<int> passphrase}) =>
    RustLib.instance.api.crateApiProfilesVaultCreate(passphrase: passphrase);

/// Join an existing vault on this device with the passphrase → `ProfileInfo`.
Future<String> vaultJoinWithPassphrase({required String vaultId, required List<int> passphrase}) =>
    RustLib.instance.api.crateApiProfilesVaultJoinWithPassphrase(vaultId: vaultId, passphrase: passphrase);

/// Join with the Recovery Key (24 words / QR text) → `ProfileInfo`.
Future<String> vaultJoinWithRecoveryKey({
  required String vaultId,
  required List<int> recoveryInput,
  Uint8List? newPassphrase,
}) => RustLib.instance.api.crateApiProfilesVaultJoinWithRecoveryKey(
  vaultId: vaultId,
  recoveryInput: recoveryInput,
  newPassphrase: newPassphrase,
);

Future<void> vaultUnlockWithPassphrase({required List<int> passphrase}) =>
    RustLib.instance.api.crateApiProfilesVaultUnlockWithPassphrase(passphrase: passphrase);

/// OS / biometric unlock via the device envelope. Needs a fresh grant of
/// the OS authenticator (see [`vault_unlock_with_device_attested`]); without
/// one it fails with `os_auth_failed`.
Future<void> vaultUnlockWithDevice() => RustLib.instance.api.crateApiProfilesVaultUnlockWithDevice();

/// Unlock with the device envelope after the UI's OS prompt (Touch ID)
/// succeeded **just now**: grants the core's authenticator once, then
/// unlocks (the device key never leaves the core).
Future<void> vaultUnlockWithDeviceAttested() => RustLib.instance.api.crateApiProfilesVaultUnlockWithDeviceAttested();

/// Forgot passphrase on a trusted device after the UI's OS prompt
/// succeeded just now (see [`vault_unlock_with_device_attested`]).
Future<void> vaultResetPassphraseWithDeviceAttested({required List<int> next}) =>
    RustLib.instance.api.crateApiProfilesVaultResetPassphraseWithDeviceAttested(next: next);

/// Whether "Unlock with Touch ID / Windows Hello" can be offered →
/// `DeviceUnlockDto` (`available`, `kind`, `has_device_envelope`,
/// `not_enrolled`).
Future<String> vaultDeviceUnlockInfo() => RustLib.instance.api.crateApiProfilesVaultDeviceUnlockInfo();

/// Change this profile's local opt-in. Enabling must follow a successful
/// native OS prompt just now; the core consumes the grant and verifies the
/// device envelope. Disabling needs an unlocked vault but no OS prompt.
Future<void> vaultSetDeviceUnlockEnabledAttested({required bool enabled}) =>
    RustLib.instance.api.crateApiProfilesVaultSetDeviceUnlockEnabledAttested(enabled: enabled);

Future<void> vaultUnlockWithRecoveryKey({required List<int> recoveryInput}) =>
    RustLib.instance.api.crateApiProfilesVaultUnlockWithRecoveryKey(recoveryInput: recoveryInput);

Future<bool> vaultVerifyPassphrase({required List<int> passphrase}) =>
    RustLib.instance.api.crateApiProfilesVaultVerifyPassphrase(passphrase: passphrase);

Future<void> vaultLock() => RustLib.instance.api.crateApiProfilesVaultLock();

Future<bool> vaultIsUnlocked() => RustLib.instance.api.crateApiProfilesVaultIsUnlocked();

/// Whether the mandatory Recovery Kit check of the open profile is still
/// pending — persisted by the core, so it survives restarts (also reported
/// as `ProfileInfo.recovery_kit_pending`).
Future<bool> vaultHasPendingRecoveryKit() => RustLib.instance.api.crateApiProfilesVaultHasPendingRecoveryKit();

/// Whether the kit itself is still in memory (the 3-word check can run);
/// `false` after a restart — offer to regenerate it then.
Future<bool> vaultRecoveryKitAvailable() => RustLib.instance.api.crateApiProfilesVaultRecoveryKitAvailable();

/// The user passed the 3-word check: forget the pending kit.
Future<void> vaultAcknowledgeRecoveryKit() => RustLib.instance.api.crateApiProfilesVaultAcknowledgeRecoveryKit();

/// New Recovery Key (the old one stops working) → `RecoveryKitDto`.
Future<String> vaultRegenerateRecoveryKit() => RustLib.instance.api.crateApiProfilesVaultRegenerateRecoveryKit();

Future<void> vaultChangePassphrase({required List<int> current, required List<int> next}) =>
    RustLib.instance.api.crateApiProfilesVaultChangePassphrase(current: current, next: next);

/// Forgot passphrase on a trusted device (OS authentication).
Future<void> vaultResetPassphraseWithDevice({required List<int> next}) =>
    RustLib.instance.api.crateApiProfilesVaultResetPassphraseWithDevice(next: next);

/// Forgot passphrase, Recovery Key: unlock + set a new passphrase.
Future<void> vaultResetPassphraseWithRecoveryKey({required List<int> recoveryInput, required List<int> next}) =>
    RustLib.instance.api.crateApiProfilesVaultResetPassphraseWithRecoveryKey(recoveryInput: recoveryInput, next: next);
