// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `error`, `fingerprint`, `input`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

Future<RdpCertificate> rdpProbeCertificate({required String address, required int port}) =>
    RustLib.instance.api.crateApiRdpRdpProbeCertificate(address: address, port: port);

Future<RdpSessionInfo> rdpConnect({
  required RdpConnection options,
  required List<int> password,
  required String certificateSha256,
}) => RustLib.instance.api.crateApiRdpRdpConnect(
  options: options,
  password: password,
  certificateSha256: certificateSha256,
);

Future<RdpSessionInfo> rdpConnectWithPermissions({
  required RdpConnection options,
  required List<int> password,
  required String certificateSha256,
  required RdpPermissions permissions,
}) => RustLib.instance.api.crateApiRdpRdpConnectWithPermissions(
  options: options,
  password: password,
  certificateSha256: certificateSha256,
  permissions: permissions,
);

Future<RdpCapabilities> rdpCapabilities() => RustLib.instance.api.crateApiRdpRdpCapabilities();

Future<RdpDirectoryGrant?> rdpPickDirectory() => RustLib.instance.api.crateApiRdpRdpPickDirectory();

Future<void> rdpReleaseDirectoryGrant({required String grantId}) =>
    RustLib.instance.api.crateApiRdpRdpReleaseDirectoryGrant(grantId: grantId);

Future<void> rdpSetPermissions({required String sessionId, required RdpPermissions permissions}) =>
    RustLib.instance.api.crateApiRdpRdpSetPermissions(sessionId: sessionId, permissions: permissions);

Future<RdpPermissions> rdpPermissions({required String sessionId}) =>
    RustLib.instance.api.crateApiRdpRdpPermissions(sessionId: sessionId);

Future<void> rdpOfferClipboardText({required String sessionId, required String text}) =>
    RustLib.instance.api.crateApiRdpRdpOfferClipboardText(sessionId: sessionId, text: text);

Future<void> rdpRequestClipboardText({required String sessionId}) =>
    RustLib.instance.api.crateApiRdpRdpRequestClipboardText(sessionId: sessionId);

Future<String?> rdpTakeClipboardText({required String sessionId}) =>
    RustLib.instance.api.crateApiRdpRdpTakeClipboardText(sessionId: sessionId);

Future<RdpPoll> rdpPoll({required String sessionId}) => RustLib.instance.api.crateApiRdpRdpPoll(sessionId: sessionId);

Future<void> rdpSendInput({required String sessionId, required List<RdpInputMessage> messages}) =>
    RustLib.instance.api.crateApiRdpRdpSendInput(sessionId: sessionId, messages: messages);

Future<void> rdpDisconnect({required String sessionId}) =>
    RustLib.instance.api.crateApiRdpRdpDisconnect(sessionId: sessionId);

class RdpCapabilities {
  final bool clipboardSupported;
  final bool folderSupported;

  const RdpCapabilities({required this.clipboardSupported, required this.folderSupported});

  @override
  int get hashCode => clipboardSupported.hashCode ^ folderSupported.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpCapabilities &&
          runtimeType == other.runtimeType &&
          clipboardSupported == other.clipboardSupported &&
          folderSupported == other.folderSupported;
}

class RdpCertificate {
  final String address;
  final int port;
  final String sha256;

  const RdpCertificate({required this.address, required this.port, required this.sha256});

  @override
  int get hashCode => address.hashCode ^ port.hashCode ^ sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpCertificate &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          port == other.port &&
          sha256 == other.sha256;
}

class RdpConnection {
  final String address;
  final int port;
  final String username;
  final String domain;
  final int width;
  final int height;

  const RdpConnection({
    required this.address,
    required this.port,
    required this.username,
    required this.domain,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      address.hashCode ^ port.hashCode ^ username.hashCode ^ domain.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpConnection &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          port == other.port &&
          username == other.username &&
          domain == other.domain &&
          width == other.width &&
          height == other.height;
}

class RdpDirectoryGrant {
  final String id;
  final String name;

  const RdpDirectoryGrant({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpDirectoryGrant && runtimeType == other.runtimeType && id == other.id && name == other.name;
}

/// Flat, bounded input DTO to avoid transporting pixel data or secrets in JSON.
class RdpInputMessage {
  /// unicode / scancode / pointer / wheel / resize / release_all.
  final String kind;
  final String text;
  final int code;
  final bool down;
  final bool extended;
  final int x;
  final int y;

  /// empty / left / middle / right. Position precedes the button event.
  final String button;
  final int vertical;
  final int horizontal;
  final int width;
  final int height;

  const RdpInputMessage({
    required this.kind,
    required this.text,
    required this.code,
    required this.down,
    required this.extended,
    required this.x,
    required this.y,
    required this.button,
    required this.vertical,
    required this.horizontal,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      text.hashCode ^
      code.hashCode ^
      down.hashCode ^
      extended.hashCode ^
      x.hashCode ^
      y.hashCode ^
      button.hashCode ^
      vertical.hashCode ^
      horizontal.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpInputMessage &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          text == other.text &&
          code == other.code &&
          down == other.down &&
          extended == other.extended &&
          x == other.x &&
          y == other.y &&
          button == other.button &&
          vertical == other.vertical &&
          horizontal == other.horizontal &&
          width == other.width &&
          height == other.height;
}

class RdpPermissions {
  final bool clipboardEnabled;
  final String? directoryGrantId;
  final bool directoryWritable;

  const RdpPermissions({required this.clipboardEnabled, this.directoryGrantId, required this.directoryWritable});

  static Future<RdpPermissions> default_() => RustLib.instance.api.crateApiRdpRdpPermissionsDefault();

  @override
  int get hashCode => clipboardEnabled.hashCode ^ directoryGrantId.hashCode ^ directoryWritable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpPermissions &&
          runtimeType == other.runtimeType &&
          clipboardEnabled == other.clipboardEnabled &&
          directoryGrantId == other.directoryGrantId &&
          directoryWritable == other.directoryWritable;
}

class RdpPixels {
  final int sequence;
  final int width;
  final int height;
  final Uint8List rgba;

  const RdpPixels({required this.sequence, required this.width, required this.height, required this.rgba});

  @override
  int get hashCode => sequence.hashCode ^ width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpPixels &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}

class RdpPoll {
  /// connecting / connected / disconnected / failed.
  final String phase;
  final String? errorCode;

  /// disabled / pending / ready / denied / unavailable; independent of connection phase.
  final String folderStatus;
  final RdpPixels? frame;

  const RdpPoll({required this.phase, this.errorCode, required this.folderStatus, this.frame});

  @override
  int get hashCode => phase.hashCode ^ errorCode.hashCode ^ folderStatus.hashCode ^ frame.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpPoll &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          errorCode == other.errorCode &&
          folderStatus == other.folderStatus &&
          frame == other.frame;
}

class RdpSessionInfo {
  final String id;
  final int width;
  final int height;

  const RdpSessionInfo({required this.id, required this.width, required this.height});

  @override
  int get hashCode => id.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpSessionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          width == other.width &&
          height == other.height;
}
