// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'rdp.dart';

// These functions are ignored because they are not marked as `pub`: `error`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `from`

Future<RdpSavedHostTicket> rdpSavedHostProbe({required String hostId}) =>
    RustLib.instance.api.crateApiRdpHostsRdpSavedHostProbe(hostId: hostId);

Future<RdpSessionInfo> rdpSavedHostConnect({
  required RdpSavedHostTicket ticket,
  Uint8List? password,
  required RdpPermissions permissions,
}) => RustLib.instance.api.crateApiRdpHostsRdpSavedHostConnect(
  ticket: ticket,
  password: password,
  permissions: permissions,
);

class RdpSavedHostTicket {
  final String hostId;
  final String name;
  final String address;
  final int port;
  final String username;
  final String domain;
  final int width;
  final int height;
  final String fingerprint;
  final String snapshotStamp;
  final bool hasSavedPassword;

  const RdpSavedHostTicket({
    required this.hostId,
    required this.name,
    required this.address,
    required this.port,
    required this.username,
    required this.domain,
    required this.width,
    required this.height,
    required this.fingerprint,
    required this.snapshotStamp,
    required this.hasSavedPassword,
  });

  @override
  int get hashCode =>
      hostId.hashCode ^
      name.hashCode ^
      address.hashCode ^
      port.hashCode ^
      username.hashCode ^
      domain.hashCode ^
      width.hashCode ^
      height.hashCode ^
      fingerprint.hashCode ^
      snapshotStamp.hashCode ^
      hasSavedPassword.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpSavedHostTicket &&
          runtimeType == other.runtimeType &&
          hostId == other.hostId &&
          name == other.name &&
          address == other.address &&
          port == other.port &&
          username == other.username &&
          domain == other.domain &&
          width == other.width &&
          height == other.height &&
          fingerprint == other.fingerprint &&
          snapshotStamp == other.snapshotStamp &&
          hasSavedPassword == other.hasSavedPassword;
}
