// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `open_with`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// Entries of `path` with full metadata → `Vec<RemoteFileInfoDto>`.
Future<String> sftpListDetailed({required String sftpId, required String path}) =>
    RustLib.instance.api.crateApiSftpSftpListDetailed(sftpId: sftpId, path: path);

/// `lstat` of one entry (link target filled) → `RemoteFileInfoDto`.
Future<String> sftpStat({required String sftpId, required String path}) =>
    RustLib.instance.api.crateApiSftpSftpStat(sftpId: sftpId, path: path);

/// Canonical absolute directory for a typed path (`~`, relative to `base`,
/// `..`); `not_found` + reason `directory_not_found` if it is not one.
Future<String> sftpResolveDirectory({required String sftpId, required String input, required String base}) =>
    RustLib.instance.api.crateApiSftpSftpResolveDirectory(sftpId: sftpId, input: input, base: base);

/// `chmod` (`mode & 0o7777`).
Future<void> sftpChmod({required String sftpId, required String path, required int mode}) =>
    RustLib.instance.api.crateApiSftpSftpChmod(sftpId: sftpId, path: path, mode: mode);

/// Empty regular file, exclusive (`already_exists` if taken).
Future<void> sftpCreateFile({required String sftpId, required String path}) =>
    RustLib.instance.api.crateApiSftpSftpCreateFile(sftpId: sftpId, path: path);

/// Recursive server-side copy (`already_exists` if `to` exists).
Future<void> sftpDuplicate({required String sftpId, required String from, required String to}) =>
    RustLib.instance.api.crateApiSftpSftpDuplicate(sftpId: sftpId, from: from, to: to);

/// At most `max_bytes` (≤ 8 MiB) from the start of a regular file.
Future<SftpPreview> sftpReadPreview({required String sftpId, required String path, required int maxBytes}) =>
    RustLib.instance.api.crateApiSftpSftpReadPreview(sftpId: sftpId, path: path, maxBytes: maxBytes);

/// All transfer jobs of this unlock (`Vec<TransferJobDto>`, newest first).
Future<String> sftpTransfers() => RustLib.instance.api.crateApiSftpSftpTransfers();

/// Remove completed, failed and cancelled jobs.
Future<void> sftpClearFinishedTransfers() => RustLib.instance.api.crateApiSftpSftpClearFinishedTransfers();

/// Open a remote file in an external application; saves are uploaded
/// (`EditSessionDto`). `payload_too_large` above 50 MiB, `invalid_input`
/// for anything but a regular file.
Future<String> editOpen({required String sftpId, required String remotePath, String? openWithJson}) =>
    RustLib.instance.api.crateApiSftpEditOpen(sftpId: sftpId, remotePath: remotePath, openWithJson: openWithJson);

/// Active edit sessions of the profile → `Vec<EditSessionDto>` (empty
/// while locked).
Future<String> editSessions() => RustLib.instance.api.crateApiSftpEditSessions();

/// "Sync now" / "Retry" → resulting `EditStatusDto`.
Future<String> editSyncNow({required String sessionId}) =>
    RustLib.instance.api.crateApiSftpEditSyncNow(sessionId: sessionId);

/// Open the working copy again (`None` = the session's application).
Future<void> editReopen({required String sessionId, String? openWithJson}) =>
    RustLib.instance.api.crateApiSftpEditReopen(sessionId: sessionId, openWithJson: openWithJson);

/// Show the working copy in Finder / Explorer.
Future<void> editReveal({required String sessionId}) =>
    RustLib.instance.api.crateApiSftpEditReveal(sessionId: sessionId);

/// Resolve a conflict; the saved remote copy's path for
/// `KeepRemoteCopyLocally`.
Future<String?> editResolve({required String sessionId, required EditConflictChoice resolution}) =>
    RustLib.instance.api.crateApiSftpEditResolve(sessionId: sessionId, resolution: resolution);

/// End a session → `EditStopOutcomeDto`.
Future<String> editStop({required String sessionId, required EditStopChoice mode}) =>
    RustLib.instance.api.crateApiSftpEditStop(sessionId: sessionId, mode: mode);

/// Working copies left by earlier runs → `Vec<EditLeftoverDto>`.
Future<String> editLeftovers() => RustLib.instance.api.crateApiSftpEditLeftovers();

/// Continue a leftover through `sftp_id` → `EditSessionDto`.
Future<String> editResume({required String sessionId, required String sftpId, String? openWithJson}) =>
    RustLib.instance.api.crateApiSftpEditResume(sessionId: sessionId, sftpId: sftpId, openWithJson: openWithJson);

/// Securely remove one leftover.
Future<void> editDiscardLeftover({required String sessionId}) =>
    RustLib.instance.api.crateApiSftpEditDiscardLeftover(sessionId: sessionId);

/// How to resolve an edit conflict.
enum EditConflictChoice {
  /// Upload the local copy over the changed remote file.
  overwriteRemote,

  /// Save the remote version next to the working copy and open it.
  keepRemoteCopyLocally,

  /// Replace the working copy with the remote version.
  discardLocal,
}

/// How an edit session ends.
enum EditStopChoice {
  /// Upload pending changes, then remove the working copy (stays open on
  /// conflict / failure; the outcome says why).
  upload,

  /// Like `Upload`, but keep the files for recovery instead of asking.
  uploadOrKeep,

  /// Stop watching, keep the working copy (a leftover).
  keepFiles,

  /// Remove the working copy without uploading.
  discard,
}

/// A bounded prefix of a remote file (Quick Look; never written to disk).
class SftpPreview {
  final String path;
  final Uint8List data;

  /// Size of the whole remote file.
  final int totalSize;

  const SftpPreview({required this.path, required this.data, required this.totalSize});

  @override
  int get hashCode => path.hashCode ^ data.hashCode ^ totalSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SftpPreview &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          data == other.data &&
          totalSize == other.totalSize;
}
