// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> sharingStatus() => RustLib.instance.api.crateApiSharingSharingStatus();

Future<String> sharingIdentity() => RustLib.instance.api.crateApiSharingSharingIdentity();

Future<String> sharingDiscover({required String email}) =>
    RustLib.instance.api.crateApiSharingSharingDiscover(email: email);

Future<String> sharingList({required bool refresh}) =>
    RustLib.instance.api.crateApiSharingSharingList(refresh: refresh);

Future<String> sharingInspect({required String id}) => RustLib.instance.api.crateApiSharingSharingInspect(id: id);

Future<String> sharingAccept({required String id, required String confirmedOwnerCode}) =>
    RustLib.instance.api.crateApiSharingSharingAccept(id: id, confirmedOwnerCode: confirmedOwnerCode);

Future<String> sharingPreviewHost({required String id, required bool includeNotes}) =>
    RustLib.instance.api.crateApiSharingSharingPreviewHost(id: id, includeNotes: includeNotes);

Future<String> sharingPreviewSnippet({required String id}) =>
    RustLib.instance.api.crateApiSharingSharingPreviewSnippet(id: id);

Future<String> sharingPublish({required String projectionJson, required String grantsJson}) =>
    RustLib.instance.api.crateApiSharingSharingPublish(projectionJson: projectionJson, grantsJson: grantsJson);

Future<String> sharingEdit({required String id, required String projectionJson}) =>
    RustLib.instance.api.crateApiSharingSharingEdit(id: id, projectionJson: projectionJson);

Future<String> sharingRotate({required String id, required String grantsJson}) =>
    RustLib.instance.api.crateApiSharingSharingRotate(id: id, grantsJson: grantsJson);

Future<void> sharingDelete({required String id}) => RustLib.instance.api.crateApiSharingSharingDelete(id: id);

Future<String> sharingOutbox() => RustLib.instance.api.crateApiSharingSharingOutbox();

Future<String> sharingFlush() => RustLib.instance.api.crateApiSharingSharingFlush();

Future<String> sharingReconcile({required String id, required String confirmedOwnerCode}) =>
    RustLib.instance.api.crateApiSharingSharingReconcile(id: id, confirmedOwnerCode: confirmedOwnerCode);

Future<String> sharingDiscardPending({required String id}) =>
    RustLib.instance.api.crateApiSharingSharingDiscardPending(id: id);

Future<String> sharingPreviewSecret({required String id, required bool passphrase}) =>
    RustLib.instance.api.crateApiSharingSharingPreviewSecret(id: id, passphrase: passphrase);

Future<String> sharingPreviewGroup({required String id, required String childrenJson}) =>
    RustLib.instance.api.crateApiSharingSharingPreviewGroup(id: id, childrenJson: childrenJson);

Future<String> sharingPublishSecret({required String id, required bool passphrase, required String grantsJson}) =>
    RustLib.instance.api.crateApiSharingSharingPublishSecret(id: id, passphrase: passphrase, grantsJson: grantsJson);

Future<Uint8List> sharingRevealSecret({required String id}) =>
    RustLib.instance.api.crateApiSharingSharingRevealSecret(id: id);

Future<String> sharingCopyHost({required String id, String? credentialId}) =>
    RustLib.instance.api.crateApiSharingSharingCopyHost(id: id, credentialId: credentialId);

Future<String> sharingCopySnippet({required String id}) =>
    RustLib.instance.api.crateApiSharingSharingCopySnippet(id: id);

Future<String> sharingRefreshBoundHost({required String id, required bool confirmEndpointChange}) =>
    RustLib.instance.api.crateApiSharingSharingRefreshBoundHost(id: id, confirmEndpointChange: confirmEndpointChange);

Future<String> sharingDetachHost({required String id}) => RustLib.instance.api.crateApiSharingSharingDetachHost(id: id);

Future<String> sharingEditSecret({required String id, required List<int> value}) =>
    RustLib.instance.api.crateApiSharingSharingEditSecret(id: id, value: value);

Future<String> sharingCopySecretCredential({required String id}) =>
    RustLib.instance.api.crateApiSharingSharingCopySecretCredential(id: id);

Future<String> sharingRefreshBoundHostExpected({required String id, required String address, required int port}) =>
    RustLib.instance.api.crateApiSharingSharingRefreshBoundHostExpected(id: id, address: address, port: port);
