// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `data`, `end`, `failed`, `forward_transfer`, `from_chunk`, `from_job`, `start_streamed`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Open a PTY shell to a host; returns once connected (host-key and
/// password prompts arrive on `core_prompts` meanwhile) → `TerminalInfoDto`.
Future<String> terminalOpen({required String hostId, required int cols, required int rows}) =>
    RustLib.instance.api.crateApiSshTerminalOpen(hostId: hostId, cols: cols, rows: rows);

/// Output of a terminal: the scrollback snapshot as the first `Data` frame,
/// then live output, ending with `Closed` / `Failed`.
Stream<TerminalFrame> terminalAttach({required String terminalId}) =>
    RustLib.instance.api.crateApiSshTerminalAttach(terminalId: terminalId);

/// Keyboard / paste input (UTF-8 bytes).
Future<void> terminalWrite({required String terminalId, required List<int> data}) =>
    RustLib.instance.api.crateApiSshTerminalWrite(terminalId: terminalId, data: data);

Future<void> terminalResize({required String terminalId, required int cols, required int rows}) =>
    RustLib.instance.api.crateApiSshTerminalResize(terminalId: terminalId, cols: cols, rows: rows);

/// Close the channel and forget the (local-only) scrollback.
Future<void> terminalClose({required String terminalId}) =>
    RustLib.instance.api.crateApiSshTerminalClose(terminalId: terminalId);

/// `TerminalInfoDto`.
Future<String> terminalInfo({required String terminalId}) =>
    RustLib.instance.api.crateApiSshTerminalInfo(terminalId: terminalId);

/// Start a saved tunnel → `TunnelStatusDto`.
Future<String> tunnelStart({required String tunnelId}) =>
    RustLib.instance.api.crateApiSshTunnelStart(tunnelId: tunnelId);

Future<void> tunnelStop({required String tunnelId}) => RustLib.instance.api.crateApiSshTunnelStop(tunnelId: tunnelId);

/// `Vec<TunnelStatusDto>` of running / failed tunnels (empty while locked).
Future<String> tunnelStatuses() => RustLib.instance.api.crateApiSshTunnelStatuses();

/// Open an SFTP session → its id.
Future<String> sftpOpen({required String hostId}) => RustLib.instance.api.crateApiSshSftpOpen(hostId: hostId);

Future<void> sftpClose({required String sftpId}) => RustLib.instance.api.crateApiSshSftpClose(sftpId: sftpId);

Future<String> sftpHome({required String sftpId}) => RustLib.instance.api.crateApiSshSftpHome(sftpId: sftpId);

/// `Vec<RemoteEntryDto>`.
Future<String> sftpList({required String sftpId, required String path}) =>
    RustLib.instance.api.crateApiSshSftpList(sftpId: sftpId, path: path);

Future<void> sftpMkdir({required String sftpId, required String path}) =>
    RustLib.instance.api.crateApiSshSftpMkdir(sftpId: sftpId, path: path);

Future<void> sftpRename({required String sftpId, required String from, required String to}) =>
    RustLib.instance.api.crateApiSshSftpRename(sftpId: sftpId, from: from, to: to);

Future<void> sftpRemove({required String sftpId, required String path, required bool recursive}) =>
    RustLib.instance.api.crateApiSshSftpRemove(sftpId: sftpId, path: path, recursive: recursive);

/// Queue an upload (`local_path` → `remote_path`) or download
/// (`remote_path` → `local_path`) of a file **or folder** (recursive) under
/// the caller's `transfer_id`. Jobs run in the core (in parallel, up to a
/// limit) and keep running while the window is hidden.
Stream<TransferUpdate> sftpTransfer({
  required String transferId,
  required String sftpId,
  required TransferDirection direction,
  required String localPath,
  required String remotePath,
}) => RustLib.instance.api.crateApiSshSftpTransfer(
  transferId: transferId,
  sftpId: sftpId,
  direction: direction,
  localPath: localPath,
  remotePath: remotePath,
);

/// Re-queue a failed / cancelled job with the same source and destination
/// under `new_transfer_id` (the old job is removed) and stream it.
Stream<TransferUpdate> sftpRetryTransfer({required String transferId, required String newTransferId}) =>
    RustLib.instance.api.crateApiSshSftpRetryTransfer(transferId: transferId, newTransferId: newTransferId);

/// Cancel a queued or running transfer (partial files are removed).
/// `false` if it already finished (or the vault is locked).
Future<bool> sftpCancelTransfer({required String transferId}) =>
    RustLib.instance.api.crateApiSshSftpCancelTransfer(transferId: transferId);

/// One item of a terminal output stream (snapshot first, then live).
class TerminalFrame {
  final TerminalFrameKind kind;
  final Uint8List data;
  final int? exitStatus;
  final String? message;

  const TerminalFrame({required this.kind, required this.data, this.exitStatus, this.message});

  @override
  int get hashCode => kind.hashCode ^ data.hashCode ^ exitStatus.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalFrame &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          data == other.data &&
          exitStatus == other.exitStatus &&
          message == other.message;
}

/// Kind of a [`TerminalFrame`].
enum TerminalFrameKind {
  /// Output bytes (the first frame is the local scrollback snapshot).
  data,

  /// Output was dropped (slow consumer); re-attach for a fresh snapshot.
  lagged,

  /// The session ended (`exit_status`, `message` = reason). Last frame.
  closed,

  /// The session failed (`message`). Last frame.
  failed,
}

/// Direction of a transfer.
enum TransferDirection { upload, download }

/// Phase of a transfer.
enum TransferPhase { queued, running, completed, failed, cancelled }

/// Progress item of [`sftp_transfer`] / [`sftp_retry_transfer`]. The stream
/// ends after `Completed`, `Failed` or `Cancelled`.
class TransferUpdate {
  final TransferPhase phase;
  final int transferred;
  final int? total;
  final int elapsedMs;
  final BridgeError? error;

  /// Files copied so far / in total (a folder job counts every file).
  final int filesDone;
  final int filesTotal;

  /// The source is a folder (copied recursively).
  final bool isDirectory;

  /// File being copied right now.
  final String? currentPath;

  const TransferUpdate({
    required this.phase,
    required this.transferred,
    this.total,
    required this.elapsedMs,
    this.error,
    required this.filesDone,
    required this.filesTotal,
    required this.isDirectory,
    this.currentPath,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      transferred.hashCode ^
      total.hashCode ^
      elapsedMs.hashCode ^
      error.hashCode ^
      filesDone.hashCode ^
      filesTotal.hashCode ^
      isDirectory.hashCode ^
      currentPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferUpdate &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          transferred == other.transferred &&
          total == other.total &&
          elapsedMs == other.elapsedMs &&
          error == other.error &&
          filesDone == other.filesDone &&
          filesTotal == other.filesTotal &&
          isDirectory == other.isDirectory &&
          currentPath == other.currentPath;
}
