// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `digits`, `pending_codes`

Future<String> syncStatus() => RustLib.instance.api.crateApiSyncSyncStatus();

/// Push the outbox and pull now → `SyncReportDto`.
Future<String> syncNow() => RustLib.instance.api.crateApiSyncSyncNow();

/// Local → Synced (register or log in, upload the vault) → `ProfileInfo`.
Future<String> syncEnable({
  required String serverUrl,
  required String email,
  required List<int> password,
  required bool register,
}) => RustLib.instance.api.crateApiSyncSyncEnable(
  serverUrl: serverUrl,
  email: email,
  password: password,
  register: register,
);

/// Synced → Local (keeps all data); optionally revoke this device.
Future<String> syncDisconnect({required bool revokeDevice}) =>
    RustLib.instance.api.crateApiSyncSyncDisconnect(revokeDevice: revokeDevice);

/// Sign in again after the session expired → `AuthStateDto`.
Future<String> syncReauthenticate({required List<int> password, required bool allowNewDeviceIdentity}) => RustLib
    .instance
    .api
    .crateApiSyncSyncReauthenticate(password: password, allowNewDeviceIdentity: allowNewDeviceIdentity);

Future<String> devicesList() => RustLib.instance.api.crateApiSyncDevicesList();

/// This installation's verification code (6 groups of 5 digits).
Future<String> devicesOwnCode() => RustLib.instance.api.crateApiSyncDevicesOwnCode();

/// New device: ask trusted devices for approval → `OwnTrustRequestDto`.
Future<String> devicesRequestApproval({String? vaultId}) =>
    RustLib.instance.api.crateApiSyncDevicesRequestApproval(vaultId: vaultId);

/// New device, after approval: open the vault with the device key.
/// `false` = not approved yet.
Future<bool> devicesFinishApproval({String? vaultId}) =>
    RustLib.instance.api.crateApiSyncDevicesFinishApproval(vaultId: vaultId);

/// Step 1 of approving another device → `PendingApprovalDto` (show its
/// `verification_code` next to the one on the new device).
Future<String> devicesStartApproval({required String requestId}) =>
    RustLib.instance.api.crateApiSyncDevicesStartApproval(requestId: requestId);

/// Step 2, only after the user confirmed both codes match. The bridge
/// re-checks `confirmed_code` against the code the core computed in step 1
/// (`approval` error on mismatch); the core refuses without step 1.
Future<void> devicesConfirmApproval({required String requestId, required String confirmedCode}) =>
    RustLib.instance.api.crateApiSyncDevicesConfirmApproval(requestId: requestId, confirmedCode: confirmedCode);

Future<void> devicesReject({required String requestId}) =>
    RustLib.instance.api.crateApiSyncDevicesReject(requestId: requestId);

Future<void> devicesRevoke({required String deviceId, String? reason}) =>
    RustLib.instance.api.crateApiSyncDevicesRevoke(deviceId: deviceId, reason: reason);

/// → `DeviceDto`.
Future<String> devicesRename({required String deviceId, required String name}) =>
    RustLib.instance.api.crateApiSyncDevicesRename(deviceId: deviceId, name: name);
