// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/account.dart';
import 'api/ai.dart';
import 'api/app.dart';
import 'api/backup.dart';
import 'api/credentials.dart';
import 'api/enrollment.dart';
import 'api/error.dart';
import 'api/inventory.dart';
import 'api/profiles.dart';
import 'api/rdp.dart';
import 'api/rdp_hosts.dart';
import 'api/sftp.dart';
import 'api/sharing.dart';
import 'api/ssh.dart';
import 'api/sync.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<TerminalFrame> dco_decode_StreamSink_terminal_frame_Sse(dynamic raw);

  @protected
  RustStreamSink<TransferUpdate> dco_decode_StreamSink_transfer_update_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BackupHeader dco_decode_backup_header(dynamic raw);

  @protected
  BackupUnlockKind dco_decode_backup_unlock_kind(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BridgeError dco_decode_box_autoadd_bridge_error(dynamic raw);

  @protected
  CoreConfig dco_decode_box_autoadd_core_config(dynamic raw);

  @protected
  HostAuthInput dco_decode_box_autoadd_host_auth_input(dynamic raw);

  @protected
  OsAuthKindChoice dco_decode_box_autoadd_os_auth_kind_choice(dynamic raw);

  @protected
  RdpConnection dco_decode_box_autoadd_rdp_connection(dynamic raw);

  @protected
  RdpDirectoryGrant dco_decode_box_autoadd_rdp_directory_grant(dynamic raw);

  @protected
  RdpPermissions dco_decode_box_autoadd_rdp_permissions(dynamic raw);

  @protected
  RdpPixels dco_decode_box_autoadd_rdp_pixels(dynamic raw);

  @protected
  RdpSavedHostTicket dco_decode_box_autoadd_rdp_saved_host_ticket(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  CoreConfig dco_decode_core_config(dynamic raw);

  @protected
  CoreInfo dco_decode_core_info(dynamic raw);

  @protected
  EditConflictChoice dco_decode_edit_conflict_choice(dynamic raw);

  @protected
  EditStopChoice dco_decode_edit_stop_choice(dynamic raw);

  @protected
  HostAuthInput dco_decode_host_auth_input(dynamic raw);

  @protected
  HostAuthKind dco_decode_host_auth_kind(dynamic raw);

  @protected
  HostKeyAnswer dco_decode_host_key_answer(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KdfChoice dco_decode_kdf_choice(dynamic raw);

  @protected
  KeyGenChoice dco_decode_key_gen_choice(dynamic raw);

  @protected
  KeyInspectionResult dco_decode_key_inspection_result(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RdpInputMessage> dco_decode_list_rdp_input_message(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BridgeError? dco_decode_opt_box_autoadd_bridge_error(dynamic raw);

  @protected
  OsAuthKindChoice? dco_decode_opt_box_autoadd_os_auth_kind_choice(dynamic raw);

  @protected
  RdpDirectoryGrant? dco_decode_opt_box_autoadd_rdp_directory_grant(dynamic raw);

  @protected
  RdpPixels? dco_decode_opt_box_autoadd_rdp_pixels(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  OsAuthKindChoice dco_decode_os_auth_kind_choice(dynamic raw);

  @protected
  RdpCapabilities dco_decode_rdp_capabilities(dynamic raw);

  @protected
  RdpCertificate dco_decode_rdp_certificate(dynamic raw);

  @protected
  RdpConnection dco_decode_rdp_connection(dynamic raw);

  @protected
  RdpDirectoryGrant dco_decode_rdp_directory_grant(dynamic raw);

  @protected
  RdpInputMessage dco_decode_rdp_input_message(dynamic raw);

  @protected
  RdpPermissions dco_decode_rdp_permissions(dynamic raw);

  @protected
  RdpPixels dco_decode_rdp_pixels(dynamic raw);

  @protected
  RdpPoll dco_decode_rdp_poll(dynamic raw);

  @protected
  RdpSavedHostTicket dco_decode_rdp_saved_host_ticket(dynamic raw);

  @protected
  RdpSessionInfo dco_decode_rdp_session_info(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  SecureStoreChoice dco_decode_secure_store_choice(dynamic raw);

  @protected
  SftpPreview dco_decode_sftp_preview(dynamic raw);

  @protected
  TerminalFrame dco_decode_terminal_frame(dynamic raw);

  @protected
  TerminalFrameKind dco_decode_terminal_frame_kind(dynamic raw);

  @protected
  TransferDirection dco_decode_transfer_direction(dynamic raw);

  @protected
  TransferPhase dco_decode_transfer_phase(dynamic raw);

  @protected
  TransferUpdate dco_decode_transfer_update(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<TerminalFrame> sse_decode_StreamSink_terminal_frame_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<TransferUpdate> sse_decode_StreamSink_transfer_update_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BackupHeader sse_decode_backup_header(SseDeserializer deserializer);

  @protected
  BackupUnlockKind sse_decode_backup_unlock_kind(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BridgeError sse_decode_box_autoadd_bridge_error(SseDeserializer deserializer);

  @protected
  CoreConfig sse_decode_box_autoadd_core_config(SseDeserializer deserializer);

  @protected
  HostAuthInput sse_decode_box_autoadd_host_auth_input(SseDeserializer deserializer);

  @protected
  OsAuthKindChoice sse_decode_box_autoadd_os_auth_kind_choice(SseDeserializer deserializer);

  @protected
  RdpConnection sse_decode_box_autoadd_rdp_connection(SseDeserializer deserializer);

  @protected
  RdpDirectoryGrant sse_decode_box_autoadd_rdp_directory_grant(SseDeserializer deserializer);

  @protected
  RdpPermissions sse_decode_box_autoadd_rdp_permissions(SseDeserializer deserializer);

  @protected
  RdpPixels sse_decode_box_autoadd_rdp_pixels(SseDeserializer deserializer);

  @protected
  RdpSavedHostTicket sse_decode_box_autoadd_rdp_saved_host_ticket(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  CoreConfig sse_decode_core_config(SseDeserializer deserializer);

  @protected
  CoreInfo sse_decode_core_info(SseDeserializer deserializer);

  @protected
  EditConflictChoice sse_decode_edit_conflict_choice(SseDeserializer deserializer);

  @protected
  EditStopChoice sse_decode_edit_stop_choice(SseDeserializer deserializer);

  @protected
  HostAuthInput sse_decode_host_auth_input(SseDeserializer deserializer);

  @protected
  HostAuthKind sse_decode_host_auth_kind(SseDeserializer deserializer);

  @protected
  HostKeyAnswer sse_decode_host_key_answer(SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KdfChoice sse_decode_kdf_choice(SseDeserializer deserializer);

  @protected
  KeyGenChoice sse_decode_key_gen_choice(SseDeserializer deserializer);

  @protected
  KeyInspectionResult sse_decode_key_inspection_result(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RdpInputMessage> sse_decode_list_rdp_input_message(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BridgeError? sse_decode_opt_box_autoadd_bridge_error(SseDeserializer deserializer);

  @protected
  OsAuthKindChoice? sse_decode_opt_box_autoadd_os_auth_kind_choice(SseDeserializer deserializer);

  @protected
  RdpDirectoryGrant? sse_decode_opt_box_autoadd_rdp_directory_grant(SseDeserializer deserializer);

  @protected
  RdpPixels? sse_decode_opt_box_autoadd_rdp_pixels(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  OsAuthKindChoice sse_decode_os_auth_kind_choice(SseDeserializer deserializer);

  @protected
  RdpCapabilities sse_decode_rdp_capabilities(SseDeserializer deserializer);

  @protected
  RdpCertificate sse_decode_rdp_certificate(SseDeserializer deserializer);

  @protected
  RdpConnection sse_decode_rdp_connection(SseDeserializer deserializer);

  @protected
  RdpDirectoryGrant sse_decode_rdp_directory_grant(SseDeserializer deserializer);

  @protected
  RdpInputMessage sse_decode_rdp_input_message(SseDeserializer deserializer);

  @protected
  RdpPermissions sse_decode_rdp_permissions(SseDeserializer deserializer);

  @protected
  RdpPixels sse_decode_rdp_pixels(SseDeserializer deserializer);

  @protected
  RdpPoll sse_decode_rdp_poll(SseDeserializer deserializer);

  @protected
  RdpSavedHostTicket sse_decode_rdp_saved_host_ticket(SseDeserializer deserializer);

  @protected
  RdpSessionInfo sse_decode_rdp_session_info(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(SseDeserializer deserializer);

  @protected
  SecureStoreChoice sse_decode_secure_store_choice(SseDeserializer deserializer);

  @protected
  SftpPreview sse_decode_sftp_preview(SseDeserializer deserializer);

  @protected
  TerminalFrame sse_decode_terminal_frame(SseDeserializer deserializer);

  @protected
  TerminalFrameKind sse_decode_terminal_frame_kind(SseDeserializer deserializer);

  @protected
  TransferDirection sse_decode_transfer_direction(SseDeserializer deserializer);

  @protected
  TransferPhase sse_decode_transfer_phase(SseDeserializer deserializer);

  @protected
  TransferUpdate sse_decode_transfer_update(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_String_None(Map<String, String> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_String_Sse(RustStreamSink<String> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_terminal_frame_Sse(RustStreamSink<TerminalFrame> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_transfer_update_Sse(RustStreamSink<TransferUpdate> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_backup_header(BackupHeader self, SseSerializer serializer);

  @protected
  void sse_encode_backup_unlock_kind(BackupUnlockKind self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_core_config(CoreConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_host_auth_input(HostAuthInput self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_os_auth_kind_choice(OsAuthKindChoice self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rdp_connection(RdpConnection self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rdp_directory_grant(RdpDirectoryGrant self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rdp_permissions(RdpPermissions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rdp_pixels(RdpPixels self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rdp_saved_host_ticket(RdpSavedHostTicket self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_core_config(CoreConfig self, SseSerializer serializer);

  @protected
  void sse_encode_core_info(CoreInfo self, SseSerializer serializer);

  @protected
  void sse_encode_edit_conflict_choice(EditConflictChoice self, SseSerializer serializer);

  @protected
  void sse_encode_edit_stop_choice(EditStopChoice self, SseSerializer serializer);

  @protected
  void sse_encode_host_auth_input(HostAuthInput self, SseSerializer serializer);

  @protected
  void sse_encode_host_auth_kind(HostAuthKind self, SseSerializer serializer);

  @protected
  void sse_encode_host_key_answer(HostKeyAnswer self, SseSerializer serializer);

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_kdf_choice(KdfChoice self, SseSerializer serializer);

  @protected
  void sse_encode_key_gen_choice(KeyGenChoice self, SseSerializer serializer);

  @protected
  void sse_encode_key_inspection_result(KeyInspectionResult self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_rdp_input_message(List<RdpInputMessage> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_string(List<(String, String)> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_error(BridgeError? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_os_auth_kind_choice(OsAuthKindChoice? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rdp_directory_grant(RdpDirectoryGrant? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rdp_pixels(RdpPixels? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_os_auth_kind_choice(OsAuthKindChoice self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_capabilities(RdpCapabilities self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_certificate(RdpCertificate self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_connection(RdpConnection self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_directory_grant(RdpDirectoryGrant self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_input_message(RdpInputMessage self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_permissions(RdpPermissions self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_pixels(RdpPixels self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_poll(RdpPoll self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_saved_host_ticket(RdpSavedHostTicket self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_session_info(RdpSessionInfo self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string((String, String) self, SseSerializer serializer);

  @protected
  void sse_encode_secure_store_choice(SecureStoreChoice self, SseSerializer serializer);

  @protected
  void sse_encode_sftp_preview(SftpPreview self, SseSerializer serializer);

  @protected
  void sse_encode_terminal_frame(TerminalFrame self, SseSerializer serializer);

  @protected
  void sse_encode_terminal_frame_kind(TerminalFrameKind self, SseSerializer serializer);

  @protected
  void sse_encode_transfer_direction(TransferDirection self, SseSerializer serializer);

  @protected
  void sse_encode_transfer_phase(TransferPhase self, SseSerializer serializer);

  @protected
  void sse_encode_transfer_update(TransferUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) => RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;
}
