#!/bin/sh
# Runtime configuration from environment variables (all generated by the
# test harness at runtime; nothing secret is committed):
#   CC_IT_PASSWORD         password of user "tester"
#   CC_IT_AUTHORIZED_KEYS  authorized_keys content (newline separated)
#   CC_IT_USER_CA          user CA public key (TrustedUserCAKeys)
#   CC_IT_HOST_CA_KEY      host CA private key (test-only, ephemeral) used to
#                          sign the ed25519 host key -> HostCertificate
#   CC_IT_HOST_PRINCIPALS  principals for the host certificate (comma list)
set -eu
mkdir -p /etc/ssh/sshd_config.d
[ -f /etc/ssh/ssh_host_ed25519_key ] || ssh-keygen -q -t ed25519 -N '' -f /etc/ssh/ssh_host_ed25519_key
[ -f /etc/ssh/ssh_host_rsa_key ] || ssh-keygen -q -t rsa -b 3072 -N '' -f /etc/ssh/ssh_host_rsa_key
echo "tester:${CC_IT_PASSWORD:-unset-$(date +%s%N)}" | chpasswd >/dev/null 2>&1
printf '%s\n' "${CC_IT_AUTHORIZED_KEYS:-}" > /home/tester/.ssh/authorized_keys
chown tester:tester /home/tester/.ssh/authorized_keys
chmod 600 /home/tester/.ssh/authorized_keys
printf '%s\n' "${CC_IT_USER_CA:-}" > /etc/ssh/user_ca.pub
rm -f /etc/ssh/sshd_config.d/hostcert.conf
if [ -n "${CC_IT_HOST_CA_KEY:-}" ]; then
  umask 077
  printf '%s\n' "$CC_IT_HOST_CA_KEY" > /tmp/host_ca
  ssh-keygen -q -s /tmp/host_ca -I "$(hostname)" -h -n "${CC_IT_HOST_PRINCIPALS:-$(hostname)}" \
    /etc/ssh/ssh_host_ed25519_key.pub
  rm -f /tmp/host_ca
  umask 022
  echo "HostCertificate /etc/ssh/ssh_host_ed25519_key-cert.pub" > /etc/ssh/sshd_config.d/hostcert.conf
fi
# Test services reachable only from inside the docker networks:
#   7777 TCP echo, 8080 HTTP.
echo "hello from $(hostname)" > /srv/www/index.html
tcpsvd -E 0.0.0.0 7777 cat &
httpd -p 8080 -h /srv/www
exec /usr/sbin/sshd -D -e
